name: tution_wala

packages:
  - ./

scripts:
  analyze:
    exec: flutter analyze

  format:
    exec: dart format --set-exit-if-changed

  generate:
    description: generate code
    exec: dart run build_runner watch -d
